--- #YAML:1.0
name:                AnyEvent-CouchDB
version:             1.02
abstract:            a non-blocking CouchDB client based on jquery.couch.js
license:             mit
author:              
    - John BEPPU <beppu@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    AnyEvent::HTTP:                1.03
    CouchDB::View:                 0
    Data::Dump:                    0
    Data::Dump::Streamer:          0
    IO::All:                       0
    JSON::XS:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
no_index:
    directory:
        - eg
        - t
