--- #YAML:1.0
name:               AnyEvent-CouchDB
version:            1.14
abstract:           a non-blocking CouchDB client based on jquery.couch.js
author:
    - John BEPPU <beppu@cpan.org>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent::HTTP:       1.11
    CouchDB::View:        0
    Data::Dump::Streamer:  0
    IO::All:              0
    JSON::XS:             0
no_index:
    directory:
        - t
        - inc
        - eg
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
