---
abstract: 'a non-blocking CouchDB client based on jquery.couch.js'
author:
  - 'John BEPPU <beppu@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.5711, CPAN::Meta::Converter version 2.110580'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-CouchDB
no_index:
  directory:
    - t
    - inc
    - eg
requires:
  AnyEvent::HTTP: 1.11
  CouchDB::View: 0
  Data::Dump::Streamer: 0
  Exception::Class: 0
  IO::All: 0
  JSON: 0
  Scalar::Util: 0
  Scope::Guard: 0
version: 1.25
